/**
 * @description       :
 * @author            : @nttdata.com
 * @group             :
 * @last modified on  : 09-10-2023
 * @last modified by  : @nttdata.com
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   09-10-2023  @nttdata.com  Initial Version
**/
public with sharing class CEN_DebidaDiligenciaRequest {
    public String user;
    public String wSystem;
    public String first_name;
    public String last_name;
    //public String company_name;
    //public String fiscal_number;
    public String dni_ce;
    public String entity_type;
    public String opportunity;
    //public String supplier_origin;
    //public String identifier;
    //public String role;
}