/**
 * @description       :
 * @author            : @nttdata.com
 * @group             :
 * @last modified on  : 13-11-2023
 * @last modified by  : @nttdata.com
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   13-11-2023  @nttdata.com  Initial Version
**/

public with sharing class CEN_NotificationAppVecinoCentRequest {
    public String case_number;
    public String estado;
    public String subject;
    public String origen;
    public String tipo_documento;
    public String numero_documento;
}