/**
 * @description       :
 * @author            : @everis.com
 * @group             :
 * @last modified on  : 04-26-2021
 * @last modified by  : @everis.com
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   04-19-2021   @everis.com   Initial Version
 **/
public class CEN_PaymentOrderDeleteCulqiResponse {
    public String wObject { get; set; }
    public String type { get; set; }
    public String merchant_message { get; set; }
    public String user_message { get; set; }
  }