/**
 * @description       : 
 * @author            : @everis.com
 * @group             : 
 * @last modified on  : 06-08-2021
 * @last modified by  : @everis.com
 * Modifications Log 
 * Ver   Date         Author        Modification
 * 1.0   06-08-2021   @everis.com   Initial Version
**/
public with sharing class CEN_ProjectObjectResponse {
    public String idProject;
    public String status;
    public String message;
}