/**
 * @description       : 
 * @author            : @everis.com
 * @group             : 
 * @last modified on  : 07-07-2021
 * @last modified by  : @everis.com
 * Modifications Log 
 * Ver   Date         Author        Modification
 * 1.0   06-08-2021   @everis.com   Initial Version
**/
public with sharing class CEN_ProjectObjectRequest {
    public String area;
    public Boolean changeInLotsStatus;
    public String centro;
    public String codInternoSAP;
    public String idSap;
    public String descripcionProyecto;
    public String direccion;
    public String departamento;
    public String provincia;
    public String distrito;
    public String ejecutivoPostVentaAsignado;
    public String statusLots;
    public String etapa;
    public String fechaEntrega;
    public String fechaInicio;
    public String fechaVigenciaPrecio;
    public String montoMinimoDeposito;
    public String montoMinimoReserva;
    public String name;
    public String numeroLicencia;
    public String owner;
    public String maximumTermForSigningTheContract;
    public String maximumPaymentDuePeriod;
    public String registro;
    public String sociedad;
    public String statusProyecto;
    public String tipoProyecto;
    public String tipoVivienda;
    public String zona;
    public String zonaRegistrada;
}