/**
 * @description       : 
 * @author            : @everis.com
 * @group             : 
 * @last modified on  : 06-30-2021
 * @last modified by  : @everis.com
 * Modifications Log 
 * Ver   Date         Author        Modification
 * 1.0   06-14-2021   @everis.com   Initial Version
**/
public with sharing class CEN_AccountSapObjectRequest {
    public String nameAccount;
    public String lastNameAccount;
    public String typeDocument;
    public String numberDocument;
    public String phoneAccount;
    public String salesOffice;
    public String headingAccount;
    public String departamento;
    public String provincia;
    public String distrito;
    public String addressAccount;
    public String sourceMediumAccount;
    public String statusAccount;
    public String commentary;
    public String addressReference;
    public Boolean termsAccepted;
    public String sourceAccountData;
    public String codSap;
    public String emailAccount;
}