/**
 * @description       :
 * @author            : @nttdata.com
 * @group             :
 * @last modified on  : 05-09-2023
 * @last modified by  : @nttdata.com
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   05-09-2023   @nttdata.com  Initial Version
**/
public with sharing class CEN_GoogleMapsResponse {

    public ZWS_REGISTRA_URL_MAPSResponse_element ZWS_REGISTRA_URL_MAPSResponse;
    
    public class ZWS_REGISTRA_URL_MAPSResponse_element {
        public String E_MESSAGE;
    }
}