/**
 * @description       :
 * @author            : @nttdata.com
 * @group             :
 * @last modified on  : 11-20-2024
 * @last modified by  : Richard Villafana - NTT DATA
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   10-09-2024  @nttdata.com  Initial Version
**/
public with sharing class CEN_ReferidoRequest {
    public String referente;
    public String referido;
    public String fecha_landing;
    public String hora_landing;
}