/**
 * @description       : Servicio de notification SMS - Tannua
 * @author            : @nttdata.com
 * @group             :
 * @last modified on  : 22-05-2023
 * @last modified by  : @nttdata.com
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   22-05-2023   @nttdata.com  Initial Version
 **/
public without sharing class CEN_NotificationSMSResponse {
    public Boolean success { get; set; }
    public String message { get; set; }
}