public class LCH_ContactHighlightContainer {
    @AuraEnabled
    public Account Account {get; set;}
    @AuraEnabled
    public Case RelatedCase {get; set;}
    //@AuraEnabled
   //public String NPS {get;set;}
    //@AuraEnabled
    //public String CSAT {get;set;}
    @AuraEnabled
    public String photoURL {get;set;}
    //@AuraEnabled
    //public Integer CaseByPhone {get;set;}
    //@AuraEnabled
    //public Integer CaseByWeb {get;set;}
    //@AuraEnabled
    //public Integer CaseByChat {get;set;}
    //@AuraEnabled
    //public Integer CaseBySocial {get;set;}
}